name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.KMBFORAWS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/streamx1/docker-image:latest

      # Add deployment steps for first EC2 instances
      - name: Deploy to EC2 Instance 1
        uses: appleboy/ssh-action@master
        with:
          host: 18.184.210.43
          username: git-run
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop container_server3000 || true
            docker rm container_server3000 || true
            echo ${{ secrets.KMBFORAWS }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker pull ghcr.io/streamx1/docker-image:latest
            docker run -d --name container_server3000 -p 3000:3000 ghcr.io/streamx1/docker-image:latest

      # Add deployment steps for other EC2 instances: same
